### PR TITLE
`QUrl` and `QmlEngine::load_data_as(QByteArray, QUrl)`

### PR DESCRIPTION
**Pull request by Defaultldentity**

### CODE REVIEW

**Comment by Defaultldentity** [comment]
Please review carefully for safety. I'm not particularly comfortable with C++

**Comment by ogoffart** [comment]
Looks good.  But can you maybe add a test?

**Comment by ogoffart** [comment]
Thank you

**Comment by Defaultldentity** [comment]
Thank *you*

**Pull request merged**
