### PR TITLE
Cosmit for future

### PR DESCRIPTION
**Pull request by ratijas**
Hey ratijas, that's a nice little stash of commits you've got here. It would be a shame if anything were to... (proceeds to force-push origin master)

### CODE REVIEW

**Comment by ratijas** [comment]
Apparently, AppVeyor is not very reliable.  Either that, or GitHub freaked up. Just what on earth was that "failed to update crates.io index"? Anyways, retrying with new changes that cargo fmt didn't catch (namely, inside rust! wrapped in cpp! macros)...

**Comment by ratijas** [comment]
yeah, this is pretty much just a cosmetic change.  I have some more fundamental stuff on the way,  but it needs some rebasing on latest master. Have been skimming through it today , but then suddenly day-job happened 😅

stay tuned but don't worry about breaking stuff -- i'll adapt mine as needed.

**Comment by ratijas** [comment]
Since it's not much of a change, I guess I could just silently merge it like nothing special. I really like how those extra `use`s reduce cognitive load when reading e.g. `Poll` instead of `std::task::Poll`; and those interned unsafe keywords in `cpp!` look more on topic and in-line with overall style of the code base.

**Comment by ogoffart** [comment]
:+1:

**Pull request merged**
