### PR TITLE
Add wrapper around qmlRegisterModule function

### LINKED ISSUE #219: Missing API wrapper for qmlRegisterModule
## Summary 

There is no Rust function for [qmlRegisterModule](https://doc.qt.io/qt-5/qqmlengine.html#qmlRegisterModule) Qt method.

### PR DESCRIPTION
**Pull request by ratijas**
This is a rarely used feature, but is still needed in some corner-cases.

Closes #219

### CODE REVIEW

**Comment by ratijas** [comment]
The test should also be guarded with cfg.  Gotta fix tomorrow.

**Comment by ratijas** [comment]
Just added little clean-ups while I'm at it. Should be good to go now. @ogoffart ?

**Comment by ogoffart** [comment]
I don't know... I'm not convinced this is so useful...  but why not?

**Comment by ratijas** [comment]
What puzzles me, is that Qt6 didn't drop version major/minor arguments nor provided a version-less overload. Actually, this is true for all registrators listed in https://doc.qt.io/qt-6/qqmlengine.html#qmlRegisterModule — feels like an incomplete refactoring or just a backward compatibility, I don't know…

**Comment by ratijas** [comment]
GitHub is weird. I used "rebase & merge" strategy, because it wouldn't make to do a branch-merge commit here. This PR was already on the tip of master, but GitHub _still insisted_ on rebasing and re-committing, so now commits have slightly different author&committer fields and lost signatures. What the heck?…

**Pull request merged**
