### PR TITLE
Add generic iterator for QList

### PR DESCRIPTION
**Pull request by Ayush1325**
Now both QStringList and QVariantList use a generic iterator for iteration implementation. The QListIterator is just a generic form of the `QVariantListIterator` that was already present.

This commit also refactors `QStringList` and `QVariantList` to separate modules inside qlist as mentioned in #235.

### CODE REVIEW

**Comment by Ayush1325** [comment]
I would like someone else to comment if anything can be improved here. I think this iterator implementation should work with any wrapper over `QList<T, K>`.

**Comment by ogoffart** [comment]
I guess it makes sense.

**Comment by Ayush1325** [comment]
@ogoffart What is the preferred way to merge. Should I use `Rebase and merge` or `Create a merge commit`?

**Comment by ogoffart** [comment]
I prefer rebase, to keep the history somewhat linear.

**Pull request merged**
