### PR TITLE
Bump some rusty dependencies

### PR DESCRIPTION
**Pull request by ratijas**
Bump dependencies:
- cpp & cpp_build from 0.5.4 to 0.5.6
- semver from 0.11 to 1 (another one reached 1.0, yay!)

### CODE REVIEW

**Review by ogoffart — APPROVED** [review]

**Comment by ratijas** [comment]
I can't believe such CI failure could have been caused by cpp & cpp_build upgrade. Investigating…

**Comment by ogoffart** [comment]
The CI failure is caused by https://github.com/rust-lang/cargo/issues/9554

**Comment by ratijas** [comment]
Shtability of Rusht, huh…

CI can't even pass the stable toolchain's tests just because one of the nightlies failed first. What to do now?  Wait until they nerf it down to a warning?

**Comment by ratijas** [comment]
I wonder, if there's an easy way to temporarily skip checks for nightly, without breaking or somehow altering CI configuration? It's not like we can do anything about the error at this point.

**Comment by ogoffart** [comment]
We can just ignore CI for this one

**Pull request merged**
