### PR TITLE
Add API wrapper for QQuickStyle::setStyle

### PR DESCRIPTION
**Pull request by timsueberkrueb**
I'm new to `qmetaobject-rs` so please correct me if this should be done differently.

### CODE REVIEW

**Comment by timsueberkrueb** [comment]
Okay, will do, thanks for the feedback!

**Comment by timsueberkrueb** [comment]
Which one would you prefer? Using the envvar or adding it to `QmlEngine`? I personally would prefer the `QQuickStyle` version as it mirrors the Qt api => therefore less surprising.

**Comment by ogoffart** [comment]
You are right, mimicking the QQuickStyle API is probably the best

**Comment by timsueberkrueb** [comment]
Done. I'm using `QString` because it matches the Qt API most closely. Is this okay or should I use `&str`?

**Comment by timsueberkrueb** [comment]
Unrelated: I think it might also make sense to use a binding generator to offer a more complete binding set on top of qmetaobject-rs, perhaps as a different crate. What do you think?

**Pull request merged**
